name: Deploy static site to S3

on:
  push:
    branches: [ "main" ]   # triggers on every push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout source
        uses: actions/checkout@v3

      - name: 🔑 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: ⬆️ Sync files to S3
        env:
          BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          aws s3 sync . s3://$BUCKET \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "README.md" \
            --delete

      - name: 🚀 Invalidate CloudFront cache
        env:
          DIST_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $DIST_ID \
            --paths "/*"
